# Generated by Django 4.1 on 2025-09-22 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresse', models.TextField(verbose_name='Adresse de livraison')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('shipped', 'Expédiée'), ('cancelled', 'Annulée')], default='pending', max_length=20, verbose_name='Statut')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du produit')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Identifiant URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix (CDF)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Quantité en stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='produits/', verbose_name='Image')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Disponible')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-cree_le'],
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire (CDF)')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventes.commande')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ventes.produit', verbose_name='Produit')),
            ],
            options={
                'verbose_name': 'Ligne de commande',
                'verbose_name_plural': 'Lignes de commande',
            },
        ),
    ]
